package com.hotcocoacup.mobiletools.xlstoresouces;

import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

import com.hotcocoacup.mobiletools.xlstoresouces.model.KeyValuePair;

public class AndroidProcessor implements Processor {

	public void process(Writer output,
			Map<String, List<KeyValuePair>> keyValuePair) throws IOException {
		
		
		output.write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
		output.write("<!-- This file has been generated by XlsToResources V" + XlsToResources.VERSION + " -->\n");
		output.write("<resources>\n");
		
		List<String> groupByList = new ArrayList<String> (keyValuePair.keySet());
		Collections.sort(groupByList, new GroupByComparator());
		
		for (String groupBy : groupByList) {
			
			output.write("\n");
			if (!"".equals(groupBy)) {
				output.write("  <!-- " + groupBy + " -->\n");
			}
			
			List<KeyValuePair> keyValues = keyValuePair.get(groupBy);
			
			for (KeyValuePair pair : keyValues) {
				String key = pair.getKey();
				key = key.replace("\\", "\\\\");
				key = key.replace("\"", "\\\"");
				output.write("  <string name=\"" + key + "\">");
				
				String value = pair.getValue();
				value = value.replace("\\", "\\\\");
				value = value.replace("\n", "\\n");
				value = value.replace("\"", "\\\"");
				value = value.replace("'", "\\'");
				value = value.replace("&", "&amp;");
				value = value.replace("<", "&lt;");
				
				output.write(value);
				output.write("</string>\n");
				
			}
			
		}
		
		output.write("\n</resources>");
		output.close();
	}

}
