package com.hotcocoacup.mobiletools.xlstoresouces;

import java.io.BufferedWriter;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

import com.hotcocoacup.mobiletools.xlstoresouces.model.KeyValuePair;

public class IosProcessor implements Processor {

	public void process(OutputStream outputStream,
			Map<String, List<KeyValuePair>> keyValuePair) throws IOException {
		
		BufferedWriter output = new BufferedWriter(new OutputStreamWriter(outputStream));
		
		output.write("/* This file has been generated by XlsToResources V" + XlsToResources.VERSION + " */\n");
		
		List<String> groupByList = new ArrayList<String> (keyValuePair.keySet());
		Collections.sort(groupByList, new GroupByComparator());
		
		for (String groupBy : groupByList) {
			
			output.write("\n");
			if (!"".equals(groupBy)) {
				output.write("/* " + groupBy + " */\n\n");
			}
			
			List<KeyValuePair> keyValues = keyValuePair.get(groupBy);
			
			for (KeyValuePair pair : keyValues) {
				String key = pair.getKey();
				key = key.replace("\\", "\\\\");
				key = key.replace("\"", "\\\"");
				output.write("\"" + key + "\" = \"");
				
				String value = pair.getValue();
				value = value.replace("\\", "\\\\");
				value = value.replace("\n", "\\n");
				value = value.replace("\"", "\\\"");
				
				output.write(value);
				output.write("\"\n");
				
			}
			
		}
		
		output.close();
		
	}

}
